spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/rest-api-basics?autoReconnect=true&useSSL=False&serverTimezone=UTC
    username: epamstudent
    password: epam@student
    driverClassName: com.mysql.cj.jdbc.Driver
    maxPoolSize: 10
  application:
    name: rest-api-basic
  server:
    port: 8080
---

spring:
  profiles: dev
  server:
    port: 8082


