spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest-api-basics?autoReconnect=true&useSSL=False&serverTimezone=UTC
    username: epamstudent
    password: epam@student
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxPoolSize: 10
  application:
    name: rest-api-basic
  server:
    port: 8080